"use client";

import React, { useState } from "react";
import { ArrowUpDown, Check, X, Scale, Filter } from "lucide-react";
import { CandidateRecommendation, EvaluatedCandidateSummary } from "@/types";
import { formatMinorUnits, formatEfficiency } from "@/lib/currency";

interface InterventionComparisonProps {
  candidates: CandidateRecommendation[];
  competingReasons?: Array<{ intervention_id: string; reason: string }>;
  selectedInterventionId?: string | null;
  summary?: EvaluatedCandidateSummary | null;
}

export function InterventionComparison({
  candidates,
  competingReasons = [],
  selectedInterventionId,
  summary,
}: InterventionComparisonProps) {
  const [filterFeasibleOnly, setFilterFeasibleOnly] = useState<boolean>(false);
  const [sortField, setSortField] = useState<"intercepted" | "collateral" | "confidence">("intercepted");
  const [sortAsc, setSortAsc] = useState<boolean>(false);

  if (candidates.length === 0) {
    return (
      <div className="rounded-xl border border-surface-border bg-surface-elevated p-6 text-sm text-slate-400 text-center">
        No candidate interventions generated by the counterfactual simulator for this decision timestamp.
      </div>
    );
  }

  const reasonMap = new Map<string, string>();
  for (const cr of competingReasons) {
    reasonMap.set(cr.intervention_id, cr.reason);
  }

  const filtered = candidates.filter((c) =>
    filterFeasibleOnly ? c.policy_feasible : true
  );

  const sorted = [...filtered].sort((a, b) => {
    let diff = 0;
    if (sortField === "intercepted") {
      diff = a.modeled_tainted_capital_intercepted - b.modeled_tainted_capital_intercepted;
    } else if (sortField === "collateral") {
      diff = a.modeled_legitimate_capital_affected - b.modeled_legitimate_capital_affected;
    } else if (sortField === "confidence") {
      diff = a.provenance_confidence - b.provenance_confidence;
    }
    return sortAsc ? diff : -diff;
  });

  const toggleSort = (field: "intercepted" | "collateral" | "confidence") => {
    if (sortField === field) {
      setSortAsc(!sortAsc);
    } else {
      setSortField(field);
      setSortAsc(false);
    }
  };

  return (
    <div className="rounded-xl border border-surface-border bg-surface-elevated p-4 lg:p-5 space-y-4 shadow-xl">
      {/* Title & Filter Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-surface-border">
        <div>
          <div className="flex items-center gap-2">
            <Scale className="h-4 w-4 text-brand-periwinkle" />
            <h2 className="text-sm font-semibold text-white tracking-wide">
              Compare interventions
            </h2>
          </div>
          {summary ? (
            <p className="text-xs text-slate-400 mt-1">
              Evaluated {summary.total_candidates_count} candidate{summary.total_candidates_count !== 1 ? "s" : ""} •{" "}
              {summary.feasible_candidates_count} feasible, {summary.infeasible_candidates_count} infeasible •{" "}
              Pareto optimal frontier: {summary.pareto_frontier_size}
            </p>
          ) : (
            <p className="text-xs text-slate-400 mt-1">
              Compare recovery of illicit funds against potential collateral impact across candidate hold points.
            </p>
          )}
        </div>

        {/* Filter Toggle */}
        <div className="flex items-center gap-2">
          <label className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-surface-raised border border-surface-border text-xs text-slate-300 cursor-pointer hover:border-slate-600 transition-colors">
            <Filter className="h-3.5 w-3.5 text-slate-400" />
            <input
              type="checkbox"
              checked={filterFeasibleOnly}
              onChange={(e) => setFilterFeasibleOnly(e.target.checked)}
              className="accent-[#6666FF] rounded cursor-pointer"
            />
            <span>Feasible only</span>
          </label>
        </div>
      </div>

      {/* Comparison Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs border-collapse">
          <thead>
            <tr className="border-b border-surface-border text-[11px] font-medium text-slate-400 tracking-wider">
              <th className="py-2.5 px-3">Status</th>
              <th className="py-2.5 px-3">Target (transfer / account)</th>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => toggleSort("intercepted")}
              >
                <div className="flex items-center gap-1">
                  <span>Illicit intercepted</span>
                  <ArrowUpDown className="h-3 w-3 text-slate-500" />
                </div>
              </th>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => toggleSort("collateral")}
              >
                <div className="flex items-center gap-1">
                  <span>Legitimate collateral</span>
                  <ArrowUpDown className="h-3 w-3 text-slate-500" />
                </div>
              </th>
              <th className="py-2.5 px-3">Scope</th>
              <th
                className="py-2.5 px-3 cursor-pointer hover:text-white transition-colors"
                onClick={() => toggleSort("confidence")}
              >
                <div className="flex items-center gap-1">
                  <span>Confidence &amp; efficiency</span>
                  <ArrowUpDown className="h-3 w-3 text-slate-500" />
                </div>
              </th>
              <th className="py-2.5 px-3">Evaluation rationale</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-surface-border/60">
            {sorted.map((cand) => {
              const isSelected = cand.intervention_id === selectedInterventionId;
              const reason = reasonMap.get(cand.intervention_id);

              return (
                <tr
                  key={cand.intervention_id}
                  className={`transition-colors ${
                    isSelected
                      ? "bg-brand-primary/10 hover:bg-brand-primary/15"
                      : "hover:bg-surface-raised/40"
                  }`}
                >
                  {/* Status / Selection */}
                  <td className="py-3 px-3">
                    {isSelected ? (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-brand-primary/20 text-[#C9E8FF] border border-brand-primary/40 font-medium text-[11px]">
                        <Check className="h-3 w-3 text-brand-celadon" /> Recommended
                      </span>
                    ) : cand.policy_feasible ? (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-surface-raised text-slate-300 text-[11px] border border-surface-border">
                        Feasible
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-risk-danger/10 text-rose-400 border border-risk-danger/30 text-[11px]">
                        <X className="h-3 w-3" /> Infeasible
                      </span>
                    )}
                  </td>

                  {/* Type & Target */}
                  <td className="py-3 px-3">
                    <div className="font-mono text-white font-medium text-xs truncate max-w-[170px] select-all">
                      {cand.target_event_id || cand.target_account_id || cand.intervention_id}
                    </div>
                    <div className="text-[11px] text-slate-400 capitalize mt-0.5">
                      {cand.intervention_type.replace(/_/g, " ")}
                    </div>
                  </td>

                  {/* Illicit Intercepted */}
                  <td className="py-3 px-3 font-mono">
                    <div className="font-semibold text-brand-celadon text-xs">
                      {formatMinorUnits(cand.modeled_tainted_capital_intercepted)}
                    </div>
                    {cand.expected_illicit_interception != null && (
                      <div className="text-[10px] text-brand-columbia">
                        Exp: {formatMinorUnits(cand.expected_illicit_interception)}
                      </div>
                    )}
                  </td>

                  {/* Legitimate Collateral */}
                  <td className="py-3 px-3 font-mono">
                    <div
                      className={`font-semibold text-xs ${
                        cand.modeled_legitimate_capital_affected > 0
                          ? "text-risk-caution"
                          : "text-slate-400"
                      }`}
                    >
                      {formatMinorUnits(cand.modeled_legitimate_capital_affected)}
                    </div>
                    {cand.worst_case_legitimate_impact != null && (
                      <div className="text-[10px] text-amber-400">
                        Worst: {formatMinorUnits(cand.worst_case_legitimate_impact)}
                      </div>
                    )}
                  </td>

                  {/* Scope */}
                  <td className="py-3 px-3 text-slate-300 text-xs">
                    <div>{cand.number_of_affected_edges} edge{cand.number_of_affected_edges !== 1 ? "s" : ""}</div>
                    <div className="text-[10px] text-slate-400">
                      {cand.number_of_affected_accounts} account{cand.number_of_affected_accounts !== 1 ? "s" : ""}
                    </div>
                  </td>

                  {/* Confidence & Efficiency */}
                  <td className="py-3 px-3">
                    <div className="font-medium text-slate-200 text-xs font-mono">
                      {(cand.provenance_confidence * 100).toFixed(0)}% confidence
                    </div>
                    <div className="text-[11px] text-brand-periwinkle font-mono mt-0.5">
                      Eff: {formatEfficiency(cand.recovery_efficiency)}
                    </div>
                  </td>

                  {/* Selection Evidence / Reason */}
                  <td className="py-3 px-3 max-w-[240px]">
                    <p className="text-xs text-slate-300 leading-snug">
                      {reason || cand.explanation || "Evaluated candidate under multi-objective policy."}
                    </p>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
